server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Structured JSON Logs
    log_format json_logs escape=json
      '{"time_local":"$time_local",'
      '"remote_addr":"$remote_addr",'
      '"request":"$request",'
      '"status": "$status",'
      '"body_bytes_sent":"$body_bytes_sent",'
      '"http_user_agent":"$http_user_agent"}';

    access_log /var/log/nginx/access.log json_logs;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # Health Endpoint returning structured JSON
    location = /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"healthy","service":"portfolyo-ui","timestamp":"$msec"}';
    }
}
